Copaces.CityCounty.Website/Models/DataObjects/SegmentSurvey.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace Copaces.CityCounty.Website.Models.DataObjects
{
    public class SegmentSurvey
    {
        [BasicInfo]
        public string Id { get; set; }

        [BasicInfo, Display(Name = "COPACES Rating")]
        public double? CopacesRating { get; set; }

        [DistressInfo, Display(Name = "Bleed Level")]
        public int? BleedLevel { get; set; }

        [DistressInfo, Display(Name = "Bleed Percentage")]
        public double? BleedPercentage { get; set; }

        [DistressInfo, Display(Name = "Block Level")]
        public int? BlockLevel { get; set; }

        [DistressInfo, Display(Name ="Block Percentage")]
        public double? BlockPercentage { get; set; }

        [DistressInfo, Display(Name = "Corrug Level")]
        public int? CorrugLevel { get; set; }

        [DistressInfo, Display(Name = "Corrug Percentage")]
        public double? CorrugPercentage { get; set; }

        [DistressInfo, Display(Name = "Cross Slope(L)")]
        public double? CrossSlopeLeft { get; set; }

        [DistressInfo, Display(Name = "Cross Slope(R)")]
        public double? CrossSlopeRight { get; set; }

        [DistressInfo, Display(Name = "Edge Level")]
        public int? EdgeLevel { get; set; }

        [DistressInfo, Display(Name = "Edge Percentage")]
        public double? EdgePercentage { get; set; }

        [BasicInfo, Display(Name = "Invent Id")]
        public int InventId { get; set; }

        [BasicInfo, Display(Name = "Is Windshield Survey")]
        public bool IsWindshieldSurvey { get; set; }

        [BasicInfo, Display(Name = "Lane Direction")]
        public String LaneDirection { get; set; }

        [BasicInfo, Display(Name = "Lane Number")]
        public String LaneNum { get; set; }

        [DistressInfo, Display(Name = "Load Level 1 (%)")]
        public double? LoadLevel1 { get; set; }

        [DistressInfo, Display(Name = "Load Level 2 (%)")]
        public double? LoadLevel2 { get; set; }

        [DistressInfo, Display(Name = "Load Level 3 (%)")]
        public double? LoadLevel3 { get; set; }

        [DistressInfo, Display(Name = "Load Level 4 (%)")]
        public double? LoadLevel4 { get; set; }

        [DistressInfo, Display(Name = "Loss of Pavement Level")]
        public int? LossPavLevel { get; set; }

        [DistressInfo, Display(Name = "Loss of Pavement (%)")]
        public double? LossPavPercentage { get; set; }

        [DistressInfo, Display(Name = "Patch/Pothole Number")]
        public int? PatchPotholeNum { get; set; }

        [BasicInfo, Display(Name = "Place Id")]
        public String PlaceId { get; set; }

        [BasicInfo]
        public String Rater { get; set; }

        [DistressInfo, Display(Name = "Ravel Level")]
        public int? RavelLevel { get; set; }

        [DistressInfo, Display(Name = "Ravel Percentage")]
        public double? RavelPercentage { get; set; }

        [DistressInfo, Display(Name = "Reflect Length")]
        public double? ReflectLength { get; set; }

        [DistressInfo, Display(Name = "Reflect Level")]
        public int? ReflectLevel { get; set; }

        [DistressInfo, Display(Name = "Reflect Number")]
        public double? ReflectNum { get; set; }

        [BasicInfo]
        public String Remarks { get; set; }

        [BasicInfo, Display(Name = "Road Id")]
        public String RoadId { get; set; }

        private DateTime? roadSurveyDate;

        [BasicInfo, Display(Name = "Road Survey Date")]
        public DateTime? RoadSurveyDate
        {
            get
            {
                var timeZone = TimeZoneInfo.FindSystemTimeZoneById("Eastern Standard Time");
                if (roadSurveyDate.HasValue)
                    return TimeZoneInfo.ConvertTimeFromUtc(roadSurveyDate.Value, timeZone);
                else
                    return null;
            }
            set { roadSurveyDate = value; }
        }

        [BasicInfo, Display(Name = "Road Survey Id")]
        public String RoadSurveyId { get; set; }

        [DistressInfo, Display(Name = "Rut In Wheelpath")]
        public double? RutInWp { get; set; }

        [DistressInfo, Display(Name = "Rut Out of Wheelpath")]
        public double? RutOutWp { get; set; }

        [BasicInfo, Display(Name = "Sample Location")]
        public String SampleLocation { get; set; }

        private DateTime? segSurveyDate;

        [BasicInfo, Display(Name = "Segment Survey Date")]
        public DateTime? SegSurveyDate
        {
            get
            {
                var timeZone = TimeZoneInfo.FindSystemTimeZoneById("Eastern Standard Time");
                if (segSurveyDate.HasValue)
                    return TimeZoneInfo.ConvertTimeFromUtc(segSurveyDate.Value, timeZone);
                return null;
            }
            set { segSurveyDate = value; }
        }

        [BasicInfo, Display(Name = "Seq Id")]
        public int? SequenceId { get; set; }

        [BasicInfo, Display(Name = "Treatment Method")]
        public String TreatmentMethod { get; set; }

        [BasicInfo, Display(Name = "Treatment Year")]
        public String TreatmentYear { get; set; }

        [BasicInfo, Display(Name = "Windshield Score")]
        public double? WindshieldScore { get; set; }

    }

}

Copaces.CityCounty.Website/Models/SegmentSurveyViewModels.cs
using System;
using System.Collections.Generic;
using Copaces.CityCounty.Website.Models.DataObjects;

namespace Copaces.CityCounty.Website.Models
{
    public class SegmentSurveyIndexViewModel
    {
        public IEnumerable<SegmentSurvey> SegmentSurveys { get; set; }
        public string SearchRoadId { get; set; }
    }

    public class SegmentSurveyDetailViewModel
    {
        public SegmentSurvey SegmentSurvey { get; set; }
        public List<SurveyPhoto> SurveyPhotos { get; set; }
    }

    public class SegmentSuveySearchViewModel
    {
        public IEnumerable<SegmentSurvey> Result { get; set; }
        public DateTime? StartDate { get; set; }
        public DateTime? EndDate { get; set; }
        public String RoadId { get; set; }
        public int? MaxRating { get; set; }

        public bool IsEmptyQuery {
            get
            {
                return !StartDate.HasValue && !EndDate.HasValue && String.IsNullOrEmpty(RoadId) && !MaxRating.HasValue;
            }
        }
    }
}

Copaces.CityCounty.Website/Controllers/SegmentSurveysController.cs
using System;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Reflection;
using System.Threading.Tasks;
using System.Web.Mvc;
using Copaces.CityCounty.Website.Models;
using Copaces.CityCounty.Website.Models.DataObjects;
using Copaces.CityCounty.Website.Utility;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;

namespace Copaces.CityCounty.Website.Controllers
{
    public class SegmentSurveysController : Controller
    {
        /// <summary>
        /// Application DB context
        /// </summary>
        ApplicationDbContext ApplicationDbContext { get; set; }

        /// <summary>
        /// User manager - attached to application DB context
        /// </summary>
        UserManager<ApplicationUser> UserManager { get; set; }

        private ApplicationUser CurrentUser {
            get {
                return User.Identity.IsAuthenticated ? UserManager.FindById(User.Identity.GetUserId()) : null;
            }
        }

        public SegmentSurveysController()
        {
            ApplicationDbContext = new ApplicationDbContext();
            UserManager = new UserManager<ApplicationUser>(new UserStore<ApplicationUser>(this.ApplicationDbContext));
        }

        // GET: SegmentSurveys
        public async Task<ActionResult> Index()
        {
            if (!User.Identity.IsAuthenticated)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

            var list = await ApiHelper.GetSegmentSurveysByPlace(new Place() {Id = CurrentUser.PlaceId});

            return View(list);
        }

        // GET: SegmentSurveys/Details/5
        public async Task<ActionResult> Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            SegmentSurvey segmentSurvey = await ApiHelper.GetSegmentSurveyById(id);
            var surveyPhotos = await ApiHelper.GetSurveyPhotosBySurvey(segmentSurvey);
            if (segmentSurvey == null)
            {
                return HttpNotFound();
            }

            return View(new SegmentSurveyDetailViewModel
            {
                SegmentSurvey = segmentSurvey,
                SurveyPhotos = surveyPhotos
            });
        }

        // GET: SegmentSurveys/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: SegmentSurveys/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "Id,BleedLevel,BleedPercentage,BlockLevel,BlockPercentage,CopacesRating,CorrugLevel,CorrugPercentage,CrossSlopeLeft,CrossSlopeRight,EdgeLevel,EdgePercentage,InventId,IsWindshieldSurvey,LaneDirection,LaneNum,LoadLevel1,LoadLevel2,LoadLevel3,LoadLevel4,LossPavLevel,LossPavPercentage,PatchPotholeNum,PlaceId,Rater,RavelLevel,RavelPercentage,ReflectLength,ReflectLevel,ReflectNum,Remarks,RoadId,RoadSurveyDate,RoadSurveyId,RutInWp,RutOutWp,SampleLocation,SegSurveyDate,SequenceId,TreatmentMethod,TreatmentYear,WindshieldScore")] SegmentSurvey segmentSurvey)
        {
            if (ModelState.IsValid)
            {
                //db.SegmentSurveys.Add(segmentSurvey);
                //await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            return View(segmentSurvey);
        }

        // GET: SegmentSurveys/Edit/5
        public async Task<ActionResult> Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            SegmentSurvey segmentSurvey = await ApiHelper.GetSegmentSurveyById(id);
            if (segmentSurvey == null)
            {
                return HttpNotFound();
            }
            return View(segmentSurvey);
        }

        // POST: SegmentSurveys/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "Id,BleedLevel,BleedPercentage,BlockLevel,BlockPercentage,CopacesRating,CorrugLevel,CorrugPercentage,CrossSlopeLeft,CrossSlopeRight,EdgeLevel,EdgePercentage,InventId,IsWindshieldSurvey,LaneDirection,LaneNum,LoadLevel1,LoadLevel2,LoadLevel3,LoadLevel4,LossPavLevel,LossPavPercentage,PatchPotholeNum,PlaceId,Rater,RavelLevel,RavelPercentage,ReflectLength,ReflectLevel,ReflectNum,Remarks,RoadId,RoadSurveyDate,RoadSurveyId,RutInWp,RutOutWp,SampleLocation,SegSurveyDate,SequenceId,TreatmentMethod,TreatmentYear,WindshieldScore")] SegmentSurvey segmentSurvey)
        {
            if (ModelState.IsValid)
            {
                //db.Entry(segmentSurvey).State = EntityState.Modified;
                //await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(segmentSurvey);
        }

        // GET: SegmentSurveys/Delete/5
        public async Task<ActionResult> Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            SegmentSurvey segmentSurvey = await ApiHelper.GetSegmentSurveyById(id);
            if (segmentSurvey == null)
            {
                return HttpNotFound();
            }
            return View(segmentSurvey);
        }

        // POST: SegmentSurveys/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(string id)
        {
            SegmentSurvey segmentSurvey = await ApiHelper.GetSegmentSurveyById(id);
            //db.SegmentSurveys.Remove(segmentSurvey);
            //await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        // GET: SegmentSurveys/Search
        public async Task<ActionResult> Search(SegmentSuveySearchViewModel searchViewModel)
        {
            if (User.Identity.IsAuthenticated)
            {
                var roads = await ApiHelper.GetRoadsByPlaceId(CurrentUser.PlaceId);
                roads.Insert(0, new Road { Id = null, Name = string.Empty });
                ViewBag.RoadList = new SelectList(roads, "Id", "Name", String.Empty);

                if (!searchViewModel.IsEmptyQuery)
                    searchViewModel.Result = (await ApiHelper.SearchSegmentSurveys(
                        start: searchViewModel.StartDate, 
                        end: searchViewModel.EndDate, 
                        placeId: CurrentUser.PlaceId,
                        roadId: searchViewModel.RoadId,
                        maxRating: searchViewModel.MaxRating));
            }

            return View(searchViewModel);
        }
    }
}

Copaces.CityCounty.Website/Views/SegmentSurveys/Delete.cshtml
@model Copaces.CityCounty.Website.Models.DataObjects.SegmentSurvey

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>SegmentSurvey</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.BleedLevel)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BleedLevel)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.BleedPercentage)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BleedPercentage)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.BlockLevel)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BlockLevel)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.BlockPercentage)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BlockPercentage)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CopacesRating)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CopacesRating)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CorrugLevel)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CorrugLevel)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CorrugPercentage)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CorrugPercentage)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CrossSlopeLeft)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CrossSlopeLeft)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CrossSlopeRight)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CrossSlopeRight)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EdgeLevel)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EdgeLevel)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EdgePercentage)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EdgePercentage)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.InventId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.InventId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IsWindshieldSurvey)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IsWindshieldSurvey)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LaneDirection)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LaneDirection)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LaneNum)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LaneNum)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LoadLevel1)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LoadLevel1)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LoadLevel2)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LoadLevel2)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LoadLevel3)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LoadLevel3)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LoadLevel4)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LoadLevel4)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LossPavLevel)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LossPavLevel)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LossPavPercentage)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LossPavPercentage)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PatchPotholeNum)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PatchPotholeNum)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PlaceId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PlaceId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Rater)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Rater)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.RavelLevel)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RavelLevel)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.RavelPercentage)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RavelPercentage)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ReflectLength)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ReflectLength)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ReflectLevel)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ReflectLevel)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ReflectNum)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ReflectNum)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Remarks)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Remarks)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.RoadId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RoadId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.RoadSurveyDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RoadSurveyDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.RoadSurveyId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RoadSurveyId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.RutInWp)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RutInWp)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.RutOutWp)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RutOutWp)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SampleLocation)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SampleLocation)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SegSurveyDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SegSurveyDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SequenceId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SequenceId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TreatmentMethod)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TreatmentMethod)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TreatmentYear)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TreatmentYear)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.WindshieldScore)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.WindshieldScore)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Copaces.CityCounty.Website/Views/SegmentSurveys/Search.cshtml
@model Copaces.CityCounty.Website.Models.SegmentSuveySearchViewModel
@{
    ViewBag.Title = "Search";
}

<link href="@Url.Content("~/Content/themes/base/datepicker.css")" rel="stylesheet" type="text/css" />
<link href="@Url.Content("~/Content/themes/base/all.css")" rel="stylesheet" type="text/css" />
<script src="@Url.Content("~/Scripts/jquery-1.10.2.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery-ui-1.11.1.js")" type="text/javascript"></script>
<script type='text/javascript'>
    $(function () {
        $('.datepicker').datepicker();
    });
</script>

<h2>Search</h2>

<!-- Search area -->
@using (Html.BeginForm("Search", "SegmentSurveys", FormMethod.Get, new { @class = "form-horizontal" }))
{
    <p>Search by data range:</p>
    <div class="form-group">
        @Html.Label("StartDate", "Start Date:", new { @class = "col-sm-2 control-label" })
        <div class="col-sm-10">
            @Html.EditorFor(m => m.StartDate, new { htmlAttributes = new { @class = "datepicker form-control" } })
        </div>
    </div>
    
    <div class="form-group">
        @Html.Label("EndDate", "End Date:", new { @class = "col-sm-2 control-label" })
        <div class="col-sm-10">
            @Html.EditorFor(m => m.EndDate, new { htmlAttributes = new { @class = "datepicker form-control" } })
        </div>
    </div>
    
    <div class="form-group">
        @Html.Label("SearchRoadId", "Road Name:", new { @class = "col-sm-2 control-label" })
        <div class="col-sm-10">
            @Html.DropDownListFor(m => m.RoadId, ViewBag.RoadList as IEnumerable<SelectListItem>, new { @class = "form-control" })
        </div>
    </div>

    <div class="form-group">
        @Html.Label("MaxRating", "Maximum Rating", new { @class = "col-sm-2 control-label" })
        <div class="col-sm-10">
            @Html.EditorFor(m => m.MaxRating,  new { htmlAttributes = new { @class = "form-control" } })
        </div>
    </div>

    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <input type="submit" value="Find" class="btn btn-default" />
        </div>
    </div>
}

@if (Model.Result != null && Model.Result.Any())
{
    var first = Model.Result.FirstOrDefault();
    <table class="table">
        <tr>
            <th>
                @Html.DisplayNameFor(model => first.RoadId)
            </th>
            <th>
                @Html.DisplayNameFor(model => first.InventId)
            </th>
            <th>
                @Html.DisplayNameFor(model => first.SequenceId)
            </th>
            <th>
                @Html.DisplayNameFor(model => first.CopacesRating)
            </th>
            <th>
                @Html.DisplayNameFor(model => first.IsWindshieldSurvey)
            </th>
            <th>
                @Html.DisplayNameFor(model => first.WindshieldScore)
            </th>
            <th>
                @Html.DisplayNameFor(model => first.LaneDirection)
            </th>
            <th>
                @Html.DisplayNameFor(model => first.LaneNum)
            </th>
            <th>
                @Html.DisplayNameFor(model => first.Rater)
            </th>
            <th>
                @Html.DisplayNameFor(model => first.Remarks)
            </th>
            <th>
                @Html.DisplayNameFor(model => first.RoadSurveyDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => first.SegSurveyDate)
            </th>
            <th></th>
        </tr>

        @foreach (var item in Model.Result)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.RoadId)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.InventId)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.SequenceId)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.CopacesRating)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.IsWindshieldSurvey)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.WindshieldScore)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.LaneDirection)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.LaneNum)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Rater)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Remarks)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.RoadSurveyDate)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.SegSurveyDate)
                </td>
                <td>
                    @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
                    @Html.ActionLink("Details", "Details", new { id = item.Id }) |
                    @Html.ActionLink("Delete", "Delete", new { id = item.Id })
                </td>
            </tr>
        }

    </table>
}